### ISSUE TITLE
Update branch-alias when creating new branch

### ISSUE THREAD

**Issue by alcaeus** [doctrine/automatic-releases#24]
When creating a new branch for a release (be it a new minor/major), the branch-alias for master should be changed as well to the next minor release after the current release. This change should be pushed as a commit to the merge-up PR when it targets master.

**Comment by Ocramius** [comment]
Not sure if this is needed, since only `master` is considered when processing the `branch-alias` directive.

Tasks like updating `Version` classes should probably be deferred to maintainers for the time being.

I'd also keel the tool language-specific as much as possible (for now)

**Comment by Ocramius** [comment]
This is no longer relevant, since the `master` branch is no longer considered "special" starting from https://github.com/laminas/automatic-releases/pull/12

Using branches such as `1.0.x`, `1.1.x`, `2.0.x` and so on will be a better long-term solution, and automatically gets rid of the complex `master`/`develop`/... branching models :)
